# Site settings
title: SyncLists
email: synclists76@gmail.com
description: "Getting things done. Together."
logo: "img/profile.png"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 424F66 #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: SyncLists

# Build settings
markdown: kramdown
permalink: pretty

#Features
feature:
  - icon: "fa-group"
    desc: "Share to-do lists with friends and family."
