# Site settings
title: SyncLists
email: synclists76@gmail.com
description: "Getting things done. Together."
logo: "img/profile.png"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 424F66 #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: SyncLists

# Build settings
markdown: kramdown
permalink: pretty

#Features
feature:
  - icon: "fa-group"
    desc: "Share to-do lists with friends and family."
  - icon: "fa-cloud-download"
    desc: "Lists updated automatically across all devices when completed or modified."
  - icon: "fa-rocket"
    desc: "Quickly add tasks one after another."
  - icon: "fa-hand-o-up"
    desc: "Swipe effortlessly to complete tasks and delete lists."

#team
team:
  - img: "img/team/adam.jpg"
    name: "Adam Hopkins"
  - img: "img/team/mitch.jpg"
    name: "Mitch Stephan"
  - img: "img/team/ethan.jpg"
    name: "Ethan Poulter"
